github: [idinium96, Nicklason]
custom: ['https://www.paypal.me/idinium', 'https://steamcommunity.com/tradeoffer/new/?partner=52862254&token=6BFJd67q', 'https://steamcommunity.com/tradeoffer/new/?partner=159805178&token=_Eq1Y3An']
