name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.4.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - run: |
        find . -name '*.map' | xargs -n1  ls -l | awk '{s+=$5} END {print "Mapping total file size: ",s/1024/1024, " MB"}'
      env:
        CI: true
